---
- name: "Test if sqlite database file exists"
  stat:
    path: "sqlite-etherpad-lite.db"
  register: restore_sqlite_file

- name: "Copy old sqlite pad database"
  copy:
    src: "sqlite-etherpad-lite.db"
    dest: "{{ etherpad.dest_dir }}/var/sqlite-etherpad-lite.db"
    owner: '{{ etherpad.user }}'
    group: '{{ etherpad.group }}'
    mode: "0755"
  when: restore_sqlite_file.stat.exists == False

- name: "Copy script migrate_SQlite2MySQL.js"
  copy:
    src: "migrate.js"
    dest: "{{ etherpad.dest_dir }}/bin/migrate_SQlite2MySQL.js"
    owner: '{{ etherpad.user }}'
    group: '{{ etherpad.group }}'
    mode: "0755"
  when: restore_sqlite_file.stat.exists == False
