---
- name: ensure the brandt users are there
  user: name="{{item.name}}"
        comment="{{item.comment}}"
        shell="{{item.shell | default('/bin/bash')}}"
        state=present
  when: ansible_hostname == "brandt"
  with_flattened:
  - users.brandt
