---
- name: "Test if piwik database dump file exists"
  stat:
    path: "/tmp/{{ mysql.restore }}"
  register: restore_file

- name: "Copy old piwik database dump"
  copy:
    src: "../files/{{ mysql.restore }}"
    dest: "/tmp/{{ mysql.restore }}"
    owner: root
    group: root
    mode: "0755"
  when: restore_file.stat.exists == False

- name: "Drop current piwik database"
  mysql_db:
    login_user: "{{ mysql.admin_user }}"
    login_password: "{{ mysql.admin_pass }}"
    db: "{{ mysql.piwik_db }}"
    state: absent

- name: "Restore old piwik database dump (this may take a while, get a coffee)"
  async: 10000000000000
  poll: 10
  mysql_db:
    login_user: "{{ mysql.admin_user }}"
    login_password: "{{ mysql.admin_pass }}"
    state: import
    name: "{{ mysql.piwik_db }}"
    target: "/tmp/{{ mysql.restore }}"

- name: "Remove old piwik database dump"
  file:
    path: "/tmp/{{ mysql.restore }}"
    state: absent

- name: "Run MySQL upgrade"
  async: 10000000000000
  poll: 10
  command: mysql_upgrade -u {{ mysql.admin_user }} --password="{{ mysql.admin_pass }}" --force
