---
- hosts: ris
  remote_user: "{{ user }}"
  sudo: yes
  tasks:

  - name: Install nginx
    apt: name=nginx state=latest

  - name: Install MongoDB Repository Key
    apt_key: id=7F0CEB10 url=http://docs.mongodb.org/10gen-gpg-key.asc state=present

  - name: Install MongoDB Repository
    apt_repository: repo='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' state=present update_cache=yes

  - name: Install MongoDB
    apt: name=mongodb-org state=latest

  - name: "Configure MongoDB: Set replica set name"
    lineinfile: dest=/etc/mongod.conf state=present insertafter="#replSet=setname" line="replSet=set01"

  - name: "Configure MongoDB: Listen to any IP address"
    lineinfile: dest=/etc/selinux/config regexp=bind_ip line="bind_ip = 0.0.0.0"

  - name: (Re-)start MongoDB
    service: name=mongod state=restarted

  - name: Install SupervisorD
    apt: name=supervisor state=latest

  - name: Download ElasticSearch
    shell: test -f elasticsearch-1.2.1.deb || wget -q -nc https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.2.1.deb

  - name: Install ElasticSearch
    apt: deb=elasticsearch-1.2.1.deb state=present

  - name: Start ElasticSearch
    service: name=elasticsearch state=started

