---
- name: Configuring brand new Ubuntu
  hosts: piwik
  gather_facts: no
  pre_tasks:
    - name: 'apt-get update'
      raw: sudo apt-get update
    - name: 'install python2' #ansible needs this older python version
      raw: sudo apt-get -y install python-simplejson
  remote_user: piwik
  roles:
    - copy-keys
    - enable-root-user-ssh-access
  become: true
  become_user: root
  become_method: sudo
