---
- hosts: brandt
  sudo: yes
  vars_files:
  - vars/users.yml
  roles:
  - users
  tags:
  - users

- hosts: brandt
  sudo: yes
  sudo_user: wahlversprechen
  roles:
  - wahlversprechen
  tags:
  - wahlversprechen